---
title: "Analysis of NEON woody plant vegetation structure data"
author: "Grace Wardell"
date: "2020-05-07"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: sandstone
    highlight: zenburn
---

# Background

The Neon Woody plant vegetation dataset (https://data.neonscience.org/data-products/DP1.10098.001) contains Structure measurements, including height, canopy diameter, and stem diameter, as well as mapped position of individual woody plants

Our analyses focus on the **relationship between individual stem height and diameter** and how that relationship **varies across growth form**

## Data 

```{r, echo=FALSE}
knitr::read_chunk(here::here("analysis.R"))
```

```{r, analysis-setup}

```

```{r}
summary(individual)
```

```{r}
DT::datatable(individual)
```

###Prepare data

```{r, analysis-filter-data}

```

```{r, analysis-fig1-barplot}

```

```{r, analysis-fig2-face-grid}

```

```{r, analysis-lm-overall}

```

```{r, analysis-lm-fig3-overall}

```

```{r, analysis-lm-fig4-growth}

```